### ISSUE TITLE
`settings.updateElement` does not work

### ISSUE THREAD

**Issue by timkelty** [barrelstrength/craft-sprout-import#38]
### Description
Subsequent imports of the following always create new products, when they should be updating (as they have matching `legacyId` data).

```
[
  {
    "@model": "barrelstrength\\sproutimport\\importers\\elements\\Entry",
    "attributes": {
      "sectionId": 4,
      "siteId": 2,
      "typeId": 4,
      "enabled": true,
      "authorId": 34
    },
    "content": {
      "title": "Sofa By-the-Inch",
      "fields": {
        "legacyId": 6,
        "patternNumber": "1288"
      }
    },
    "settings": {
      "updateElement": {
        "matchBy": "legacyId",
        "matchValue": 6,
        "matchCriteria": {
          "sectionId": 4,
          "siteId": 2
        }
      }
    }
  }
]
```

**Comment by pdaleramirez** [comment]
Fixed the issue here https://github.com/barrelstrength/craft-sprout-import/commit/9393860d367998cdda14886d7e9a8509fd6d1ca5

**Comment by timkelty** [comment]
@pdaleramirez @BenParizek This still doesn't work (I'm testing on the `bugfix/update-element-custom-field` branch). New elements are always still created.

**Comment by timkelty** [comment]
The fix doesn't work because you are ignoring the `$matchCriteria` if matchBy isn't a base attribute. In this case that doesn't work, as the matchCriteria specifies a different site.

Furthermore, I don't see any reason for the `search` param acrobatics at all…Element Queries can search custom fields as params: https://docs.craftcms.com/v3/element-queries.html#custom-field-parameters

**Comment by timkelty** [comment]
PR here: https://github.com/barrelstrength/craft-sprout-import/pull/45/

**Comment by BenParizek** [comment]
Thanks @timkelty 

Perhaps the `search` param acrobatics are something we carried over from Craft 2 that is no longer needed. We'll review and see if we can simplify this as your PR suggests.

**Comment by timkelty** [comment]
Could be. You can do that in Craft 2 as well but it was never documented very well.

If you get into a full refactor, it might make sense to just ditch matchBy/matchValue all together and let the user use the full power of an element query with matchCriteria.

**Comment by pdaleramirez** [comment]
I have tested this and it works without the search query. I merged your pull request @timkelty

**Comment by BenParizek** [comment]
@timkelty This has been fixed in the latest release. We've also done away with the `matchBy`, `matchValue`, and `matchCriteria` syntax in favor of a new `params` syntax which gives you control to do whatever you would like. All Craft 3 examples have been updated in the docs to use `params`.

``` json
[
  {
    "@model": "barrelstrength\\sproutimport\\importers\\elements\\Entry",
    "attributes": { ... },
    "content": {
      "title": "In quaerat maiores sit est rerum iusto.",
      "fields": { ... },
      "related": {
        "thumbnailImage": {
          "@model": "barrelstrength\\sproutimport\\importers\\elements\\Asset",
          "params": {
            "filename": ["ImageName03.jpg"],
            "source": "images",
            "folderId": 8
          }
        }
      }
    }
  }
]
```

**Comment by timkelty** [comment]
Thanks all!
